# Generated by Django 4.2.3 on 2023-08-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_city_city_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
