# Generated by Django 4.2.3 on 2023-08-19 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_subscription_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
